version: "3"
services:
  todo_list_api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: todo
    #command: gunicorn -w 4 --bind 0.0.0.0:5000 run:app
    command: gunicorn --bind 0.0.0.0:5000 run:app
    env_file:
      - backend/.flaskenv
    ports:
      - "5000:5000"
    volumes:
      - ./backend/todo_list_api:/todo_list_api
    depends_on:
      - mongodb
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
    - "27018:27017"
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro