language: python

python:
  - "3.8"
sudo: required

services:
  - docker

before_script:
  - pip install docker-compose
  - docker-compose up -d --build

#script: "flask run --host=0.0.0.0 & pytest tests/tests_api/test_todo.py"
script:
  - sh -c "ls tests/tests_api/"
  - sh -c "pytest -vs"
after_script:
  - docker-compose down
  - docker rmi $(sudo docker images -a -q)